In [1]:
import numpy as np
import time

In [8]:
lst = list(range(10000000))
arr = np.arange(10000000)

In [9]:
start_time = time.time()
np.sum(lst)
print('list time :', time.time() - start_time)

list time : 0.598780632019043


In [10]:
start_time = time.time()
np.sum(arr)
print('array time :', time.time() - start_time)

array time : 0.010261058807373047


#### Creating Arrays

In [13]:
# 1D array
arr1 = np.array([1,3,5,7])
arr1

array([1, 3, 5, 7])

In [14]:
# 2D array
arr2 = np.array([[1,3,5,7], [2,4,6,8]])
arr2

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [22]:
# create array of zeros, one and range (rowa, columns)
arrzeros = np.zeros((2,4))
arrones = np.ones((2,4))
arrrange = np.arange(2,10,2) # (start, end, stepsize)

print(arrzeros)
print()
print(arrones)
print()
print(arrrange)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[2 4 6 8]


#### Array Operations

In [32]:
# 1D array
a = np.array([1,3,5])
b = np.array([2,4,6])
#2D array
a2 = np.array([[1,3,5],[2,4,6]])
b2 = np.array([['a','b','c'],[1,2,3]])

In [35]:
# elements wise operations
print('addtion = ', a + b)
print('multiplication = ', a * b)
print('squared = ', a **2)
print('square root = ', np.sqrt(a + b))
print('scaler multiplication = ', a * 5)

addtion =  [ 3  7 11]
multiplication =  [ 2 12 30]
squared =  [ 1  9 25]
square root =  [1.73205081 2.64575131 3.31662479]
scaler multiplication =  [ 5 15 25]


In [41]:
a2

array([[1, 3, 5],
       [2, 4, 6]])

In [46]:
# broadcasting
print('scaler multi = ', a2* 5)
print('scaler add = ', a2 + 5)

scaler multi =  [[ 5 15 25]
 [10 20 30]]
scaler add =  [[ 6  8 10]
 [ 7  9 11]]


#### Indexing, Slicing, Reshaping

In [47]:
arr = np.array([[10,20,30],[40,50,60]])
arr

array([[10, 20, 30],
       [40, 50, 60]])

In [53]:
# indexing (rows, columns)
print(arr[0,2])
print(arr[1,2])

30
60


In [61]:
# slicing (row_start : row_end, col_start : col_end)
print(arr[:, 0:2])
print()
print(arr[:, -1])

[[10 20]
 [40 50]]

[30 60]


In [62]:
arr

array([[10, 20, 30],
       [40, 50, 60]])

In [69]:
# reshaping (ROWS, COL) basically transpose
arr1 = arr.reshape(3,2)
arr1

array([[10, 20],
       [30, 40],
       [50, 60]])

In [72]:
arr = arr1.reshape(2,3)
arr

array([[10, 20, 30],
       [40, 50, 60]])

In [78]:
np.arange(16).reshape(2,8) # row * columns = no of elements

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

#### Useful Numpy Functions

In [79]:
arr

array([[10, 20, 30],
       [40, 50, 60]])

In [88]:
print(arr.mean())
print(arr.max())
print(arr.min())
print(arr.std())
print(arr.var())

35.0
60
10
17.07825127659933
291.6666666666667


In [107]:
a3 = np.array([1,5,3,5,6, 11,5,0,0])
b3 = np.array([[1,5,3,44,5],[9,77,2,0,6]])

In [108]:
np.sort(a3)

array([ 0,  0,  1,  3,  5,  5,  5,  6, 11])

In [109]:
np.sort(b3)

array([[ 1,  3,  5,  5, 44],
       [ 0,  2,  6,  9, 77]])

In [117]:
# linspace (start, end, parts devided) -> its devide no between equal pard 
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [124]:
# random
import random
rand = np.random.randint(1,10, (3,5)) # random int between (start, end, shape of array)
rand

array([[1, 7, 2, 2, 3],
       [7, 2, 7, 1, 1],
       [1, 9, 9, 9, 8]], dtype=int32)

In [128]:
# creating 5*5 matrix
x1 = np.arange(1, 26).reshape(5,5)
print(x1)
print()
x2 = np.random.randint(1,25, (5,5))
print(x2)
print()

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

[[ 5 21  4 13 23]
 [23 12 21 20 10]
 [21 21  2  6 21]
 [ 6 11 12 24  8]
 [10  4 22 20 17]]



In [132]:
# slicing middle 3*3 matrix
x3 = x2[1:4, 1:4]
x3

array([[12, 21, 20],
       [21,  2,  6],
       [11, 12, 24]], dtype=int32)

In [135]:
# sum of each row 
np.sum(x1, axis = 1)

array([ 15,  40,  65,  90, 115])

In [136]:
# sum of each columns
np.sum(x1, axis = 0)

array([55, 60, 65, 70, 75])

#### Case Study - insurance claims record

In [138]:
claims = np.array([[12000,15000,18000],
                  [10000,13000,17000],
                  [9000,11000,16000]])
claims

array([[12000, 15000, 18000],
       [10000, 13000, 17000],
       [ 9000, 11000, 16000]])

In [141]:
print(claims[0,2])
print(claims[2,0])

18000
9000


In [148]:
print(np.sum(claims, axis = 1)) # row wise
print(np.sum(claims, axis = 0)) # columns wise

[45000 40000 36000]
[31000 39000 51000]


In [149]:
print(np.mean(claims, axis = 1)) # row wise
print(np.mean(claims, axis = 0)) # columns wise

[15000.         13333.33333333 12000.        ]
[10333.33333333 13000.         17000.        ]


In [151]:
print(np.sum(claims)) # total sum

121000


In [154]:
print(claims[claims>1300])

[12000 15000 18000 10000 13000 17000  9000 11000 16000]


#### Case Study 2

In [1]:
import numpy as np 

In [5]:
data = np.array([
    ['C001', 5, 'Excellent'],
    ['C002', 4, 'Good'],
    ['C003', 3, 'Average'],
    ['C004', 5, 'Loved'],
    ['C005', 2, 'Poor'],
    ['C006', 4, 'Good'],
    ['C007', 1, 'Terrible'],
    ['C008', 5, 'Amazing'],
])
data

array([['C001', '5', 'Excellent'],
       ['C002', '4', 'Good'],
       ['C003', '3', 'Average'],
       ['C004', '5', 'Loved'],
       ['C005', '2', 'Poor'],
       ['C006', '4', 'Good'],
       ['C007', '1', 'Terrible'],
       ['C008', '5', 'Amazing']], dtype='<U21')

In [28]:
# extracting only rating as int
ratings = data[:, 1].astype(int) # convert it into int values
len(ratings)

8

In [34]:
# avg ratings
print(ratings.mean())
print(ratings.max())
print(ratings.min())

3.625
5
1


In [56]:
feedbacks = data[:, 2].astype(str)
feedbacks

array(['Excellent', 'Good', 'Average', 'Loved', 'Poor', 'Good',
       'Terrible', 'Amazing'], dtype='<U21')

In [64]:
unique_ratings, rating_counts = np.unique(ratings, return_counts=True)

print("Unique ratings:", unique_ratings)
print("Rating counts:", rating_counts)

Unique ratings: [1 2 3 4 5]
Rating counts: [1 1 1 2 3]


In [70]:
# total no of rating count per unique rating
for i,x in zip(unique_ratings, rating_counts):
    print(f' Customer ratings : {i} -> total rating count is {x}')

 Customer ratings : 1 -> total rating count is 1
 Customer ratings : 2 -> total rating count is 1
 Customer ratings : 3 -> total rating count is 1
 Customer ratings : 4 -> total rating count is 2
 Customer ratings : 5 -> total rating count is 3


In [77]:
# feedbacks
for c,r,comment in zip(data[:,0], ratings,data[:, 2]):
    print(f'Customer number {c} and feedback with ratings {r} is : {comment}')

Customer number C001 and feedback with ratings 5 is : Excellent
Customer number C002 and feedback with ratings 4 is : Good
Customer number C003 and feedback with ratings 3 is : Average
Customer number C004 and feedback with ratings 5 is : Loved
Customer number C005 and feedback with ratings 2 is : Poor
Customer number C006 and feedback with ratings 4 is : Good
Customer number C007 and feedback with ratings 1 is : Terrible
Customer number C008 and feedback with ratings 5 is : Amazing
