In [1]:
import numpy as np

In [2]:
a = np.array([1, 2,3, 4, 5])
print(a)

[1 2 3 4 5]


In [6]:
#a = np.array([[9,8,7],[6,5,4]])

a = np.array( [[1,2,3],[5,4,6]]   )   

print(a)

[[1 2 3]
 [5 4 6]]


In [7]:
# Get Dimension
a.ndim

2

In [8]:
# Get shape
a.shape


(2, 3)

In [9]:
# Get type
a.dtype

dtype('int64')

In [10]:
# Get size of the array (bytes)
a.size

6

In [11]:
# Get size
a.itemsize

8

In [12]:
# Get Toatal size
a.nbytes

48

# Accessing / cahnging specific elements, rows, columns, etc.

In [13]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [14]:
# Get a specific element [rows, columns]
print(a[0,3])

4


In [15]:
# Get a specific row
print(a[1, :])

[ 8  9 10 11 12 13 14]


In [16]:
# Get a specif column
print(a[:, 6])

[ 7 14]


In [17]:
# Getting a little more fancy [startindex:endindex:stepsize]
print(a[0,0:6:2])
print(a[:, 2:4])

[1 3 5]
[[ 3  4]
 [10 11]]


In [18]:
# Reassigning the value of element
a[1,4] = 20 
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 20 13 14]]


# 3-D example

In [19]:

b = np.array([ [[1, 2], [3, 4]], [[5, 6], [7, 8]]      ])
print(b)            

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [21]:
# Get a specific element ( Work Outside in )
b[1,1,0]



7

In [22]:
# Replace 
b[:, 0, :] = [[9,9],[8,8]]
print(b)

[[[9 9]
  [3 4]]

 [[8 8]
  [7 8]]]


# Intializing Different Types of Arrays

In [23]:
# All Zeros Matrix
x = np.zeros((5, 4), 'float')
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [24]:
# All 1s matrix
np.ones((4,4), dtype = 'int32')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [25]:
# any other number
np.full((2,2), 50)

array([[50, 50],
       [50, 50]])

In [27]:
# Any other number (fill_like)
print(np.full_like(x.shape, 4))

[4 4]


In [ ]:
# Random decimal Numbers between 0 and 1 (4,2 are dimensions of matrix)
np.random.rand(6,3)

In [ ]:
# Random decimal numbers (a is already existing matix)
np.random.random_sample(a.shape)

In [ ]:
# Random Integer Values (3*3 is the size of matrix)
#np.random.randint(1,7, size=(3,3))
np.random.randint(1, 16, size=(3,3))

In [ ]:
np.identity(3, 'int32') #np.identity(3, 'int32'(optional))

In [ ]:
# Repeat an Array along the given axis
arr = np.array([[1,2,3]])
print(arr)
print("--------------")
r1 = np.repeat(arr, 3,axis=0)
print(r1)

In [ ]:
output = np.ones((5,5), 'int32')
print(output)
print()
y = np.zeros((3,3), 'int32')
y[1,1] = 9
print(y)
print()
output[1:4,1:4] = y
print(output)

# Mathematics

In [ ]:
a = np.array([1,2,3,4])
print(a)

In [ ]:
print(a+2)

In [ ]:
a-2

In [ ]:
a*2

In [ ]:
a/2

In [ ]:
a**2

In [ ]:
# Take the sin
np.sin(a)

## Linear Algebra

In [ ]:
# Matrix Multiplication
a = np.ones((2,3), 'int')
print(a)
print()
b = np.full((3,2), 2)
print(b)
print()
print(" matrix multiplication: ")
print(np.matmul(a,b))

In [ ]:
# Find the Determinant of the matrix
c = np.identity(3, 'int')
print(c)
print()
print(" Determinant of the matrix is :", np.linalg.det(c))

In [ ]:
# Inverse of the matrix
d = np.array([[1,4,7], [9,6,2],[4,7,10]])
print(d)
print()
print("Inverse of the matrix is :")
print(np.linalg.inv(d))

## Statistics

In [ ]:
stats  = np.array([[1,2,3], [4,5,6]])
print(stats)

In [ ]:
# Minimum values 
print(np.min(stats), "\n")
print(np.min(stats, axis=0), "\n") # Along Columns
print(np.min(stats, axis=1)) # Along rows

In [ ]:
# Maximum value
np.max(stats)

In [ ]:
# Sum
print(np.sum(stats))

# Reorganizing Array

In [ ]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

In [ ]:
# Reshaping Array
after = before.reshape(4,2)
print(after)

In [ ]:
# Vertically Stacking of matrix or vectors or arrays
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
print(np.vstack((v1,v2)))

In [ ]:
# Horizontal Stacking of matrix or vectors or arrays
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
print(np.hstack([v1,v2]))

In [ ]:
# multiple stacking of matrix or vectors or arrays
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
print(np.vstack([v1,v2,v1,v2]))

# Miscellaneous

#### Load Data from File

In [ ]:
filedata = np.genfromtxt(r"C:\Users\sumit\Desktop\test.txt", delimiter=",")
filedata = filedata.astype('int')
print(filedata)

## Boolean Masking and Advanced Indexing

In [ ]:
filedata > 50

In [ ]:
filedata[filedata>50]

In [ ]:
## You can index with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

In [ ]:
np.any(filedata > 50, axis=0)

In [ ]:
np.all(filedata > 50, axis=0)

In [ ]:
((filedata > 50) & (filedata< 100))

In [ ]:
ex = np.arange(1,31).reshape(6,5)
print(ex)

In [ ]:
print(ex[2:4,0:2])

In [ ]:
# important
ex[[0,1,2,3],[1,2,3,4]]

In [ ]:
print(ex[[0,4,5], 3:])